version: "3.7"
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  backend:
    build:
      dockerfile: Dockerfile.prod
    command: npm start
    ports:
      - "4000:3000"
  frontend:
    build:
      dockerfile: Dockerfile.prod
    command: npm run start
    ports:
      - "8080:3000"
