version: "3.7"
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "3002:5432"
  backend:
    build:
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/app:ro
  frontend:
    build:
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app
